# Generated by Django 2.1.5 on 2019-01-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drifters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_number', models.CharField(max_length=8)),
                ('platform_type', models.CharField(max_length=32)),
                ('float_serial_no', models.CharField(max_length=32)),
            ],
        ),
    ]
