# Generated by Django 2.1.5 on 2019-01-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_prof', models.IntegerField()),
                ('level_nimber', models.IntegerField()),
                ('psal_adjusted', models.FloatField()),
                ('psal_adjusted_qc', models.IntegerField()),
                ('psal_adjusted_err', models.FloatField()),
                ('pres_adjusted', models.FloatField()),
                ('pres_adjusted_qc', models.IntegerField()),
                ('pres_adjusted_err', models.FloatField()),
                ('temp_adjusted', models.FloatField()),
                ('temp_adjusted_qc', models.IntegerField()),
                ('temp_adjusted_err', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=64)),
                ('cycle_number', models.IntegerField()),
                ('direction', models.CharField(max_length=1)),
                ('data_mode', models.CharField(max_length=1)),
                ('vertical_sampling_scheme', models.CharField(max_length=256)),
                ('juld', models.DateTimeField()),
                ('juld_qc', models.IntegerField()),
                ('juld_location', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('position_qc', models.IntegerField()),
                ('drifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argo.Drifters')),
            ],
        ),
        migrations.AddField(
            model_name='measurements',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argo.Sessions'),
        ),
    ]
