# Generated by Django 2.1.5 on 2019-01-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0002_auto_20190121_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurements',
            name='n_prof',
        ),
        migrations.AddField(
            model_name='sessions',
            name='n_prof',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
