# Generated by Django 2.1.5 on 2019-01-24 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0003_auto_20190121_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment_stamp', models.DateTimeField(default=datetime.datetime(2019, 1, 25, 1, 20, 17, 501131))),
                ('file_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
