# Generated by Django 2.1.5 on 2019-01-28 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0004_syslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurements',
            old_name='level_nimber',
            new_name='level_number',
        ),
        migrations.RenameField(
            model_name='sessions',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='syslog',
            name='moment_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 28, 15, 8, 31, 181625)),
        ),
    ]
